server:
  port: 8080
spring:
  application:
    name: example-grpc-client

grpc:
  client:
    example-grpc-server:
      address: 'static://127.0.0.1:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
