server:
  port: 8080
spring:
  application:
    name: example-grpc-client

grpc:
  client:
    example-grpc-server:
      address: 'static://localhost:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      security:
        clientAuthEnabled: true
        certificateChain: classpath:certificates/client.crt
        privateKey: classpath:certificates/client.key
        trustCertCollection: classpath:certificates/trusted-server.crt.collection
